Controllers/AzureController.cs
using Azure.Storage;
using Azure.Storage.Blobs;
using Azure.Storage.Sas;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Graph;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using UploadingLagreFiles_JavaScriptFileSplit.Helpers;
using UploadingLagreFiles_JavaScriptFileSplit.Models;

namespace UploadingLagreFiles_JavaScriptFileSplit.Controllers
{
	public class AzureStorageSASResult
	{
		public string AccountName { get; set; }
		public string AccountUrl { get; set; }
		public Uri ContainerUri { get; set; }
		public string ContainerName { get; set; }
		public string BlobName { get; set; }
		public Uri SASUri { get; set; }
		public string SASToken { get; set; }
		public string SASPermission { get; set; }
		public DateTimeOffset SASExpire { get; set; }
	}

	public class AzureController : Controller
	{
		private readonly ILogger<AzureController> _logger;
		private IHostingEnvironment Environment;

		public AzureController(ILogger<AzureController> logger, IHostingEnvironment _environment)
		{
			_logger = logger;
			Environment = _environment;
		}

		//[HttpGet]
		//public IActionResult Index1()
		//{
		//	var AccountName = "vschooldev";
		//	var AccountKey = "wfm1Y3R6Oy3Ov04as8XCD7AM9R6XR0t5hrvpCg3jgnEMgw4jc+bCJubSXu5Fa3rCEpBhD8+9UjqsBksy3VR8xA==";
		//	var ConnectionString = "DefaultEndpointsProtocol=https;AccountName=vschooldev;AccountKey=wfm1Y3R6Oy3Ov04as8XCD7AM9R6XR0t5hrvpCg3jgnEMgw4jc+bCJubSXu5Fa3rCEpBhD8+9UjqsBksy3VR8xA==;EndpointSuffix=core.windows.net;";
		//	var ContainerName = "lor";
		//	var TokenExpirationMinutes = 60;
		//	var blobName = "test.zip";

		//	BlobContainerClient container = new(ConnectionString, ContainerName);

		//	if (!container.CanGenerateSasUri) return Conflict("The container can't generate SAS URI");

		//	var sasBuilder = new BlobSasBuilder
		//	{
		//		BlobContainerName = container.Name,
		//		Resource = "c",
		//		ExpiresOn = DateTimeOffset.UtcNow.AddMinutes(TokenExpirationMinutes)
		//	};

		//	sasBuilder.SetPermissions(BlobAccountSasPermissions.All);
		//	sasBuilder.SetPermissions(BlobContainerSasPermissions.All);
		//	sasBuilder.SetPermissions(BlobSasPermissions.All);

		//	var sasUri = container.GenerateSasUri(sasBuilder);

		//	var result = new AzureStorageSASResult
		//	{
		//		AccountName = container.AccountName,
		//		AccountUrl = $"{container.Uri.Scheme}://{container.Uri.Host}",
		//		ContainerName = container.Name,
		//		ContainerUri = container.Uri,
		//		BlobName = blobName,
		//		SASUri = sasUri,
		//		SASToken = sasUri.Query.TrimStart('?'),
		//		SASPermission = sasBuilder.Permissions,
		//		SASExpire = sasBuilder.ExpiresOn
		//	};

		//	return View(result);
		//}

		//[HttpGet]
		//public IActionResult Index2()
		//{
		//	var AccountName = "vschooldev";
		//	var AccountKey = "wfm1Y3R6Oy3Ov04as8XCD7AM9R6XR0t5hrvpCg3jgnEMgw4jc+bCJubSXu5Fa3rCEpBhD8+9UjqsBksy3VR8xA==";
		//	//var ConnectionString = "DefaultEndpointsProtocol=https;AccountName=vschooldev;AccountKey=wfm1Y3R6Oy3Ov04as8XCD7AM9R6XR0t5hrvpCg3jgnEMgw4jc+bCJubSXu5Fa3rCEpBhD8+9UjqsBksy3VR8xA==;EndpointSuffix=core.windows.net;";
		//	var ContainerName = "lor";
		//	var TokenExpirationMinutes = 60 * 24;
		//	var blobName = "test.zip";
		//	var SharedKey = new StorageSharedKeyCredential(AccountName, AccountKey);

		//	var blobServiceClient = new BlobServiceClient(new Uri("https://vschooldev.blob.core.windows.net"), SharedKey);

		//	var blobContainerClient = new BlobContainerClient(blobServiceClient.GetBlobContainerClient(ContainerName).Uri, SharedKey);

		//	var blobClient = new BlobClient(blobContainerClient.GetBlobClient(blobName).Uri, SharedKey);
		//	if (!blobClient.CanGenerateSasUri)
		//	{
		//		return Conflict("The blob can't generate SAS URI");
		//	}

		//	// Create a SAS token that's valid for one hour.
		//	var sasBuilder = new BlobSasBuilder()
		//	{
		//		BlobContainerName = ContainerName,
		//		BlobName = blobName,
		//		Resource = "b",
		//	};

		//	sasBuilder.StartsOn = DateTimeOffset.UtcNow;
		//	sasBuilder.ExpiresOn = DateTimeOffset.UtcNow.AddMinutes(TokenExpirationMinutes);
		//	sasBuilder.SetPermissions(BlobSasPermissions.Write);

		//	//var sasUri = blobClient.GenerateSasUri(sasBuilder);

		//	var sasToken = sasBuilder.ToSasQueryParameters(SharedKey).ToString();
		//	var sasUri = new Uri($"{blobClient.Uri}?{sasToken}");

		//	var result = new AzureStorageSASResult
		//	{
		//		AccountName = blobServiceClient.AccountName,
		//		AccountUrl = $"{blobContainerClient.Uri.Scheme}://{blobContainerClient.Uri.Host}",
		//		ContainerName = blobContainerClient.Name,
		//		ContainerUri = blobContainerClient.Uri,
		//		BlobName = blobClient.Name,
		//		SASUri = sasUri,
		//		SASToken = sasUri.Query.TrimStart('?'),
		//		SASPermission = sasBuilder.Permissions,
		//		SASExpire = sasBuilder.ExpiresOn
		//	};

		//	return View(result);
		//}

		[HttpGet]
		public IActionResult Index()
		{
			var blobName = "test.zip";
			var uri = AzureHelper.Blob.GetUploadLink(blobName);

			var result = new AzureStorageSASResult
			{
				AccountUrl = $"{uri.Scheme}://{uri.Host}",
				ContainerName = uri.LocalPath.Replace(blobName, "").Trim('/'),
				BlobName = blobName,
				SASToken = uri.Query.TrimStart('?')
			};

			return View(result);
		}

		[HttpPost]
		public IActionResult Index(string azurePath)
		{
			var filename = Path.GetFileName(azurePath);
			var localPath = this.Environment.WebRootPath + "/storage/temp/" + filename;

			if (!AzureHelper.Blob.Download(azurePath, localPath))
			{
				return Json(new { status = false, message = "can not download file" });
			}

			return Json(new { status = true });
		}

		//[HttpHead]
		//public IActionResult Index(string filename)
		//{
		//	var path = this.Environment.WebRootPath + "/storage/temp/" + filename;
		//	if (System.IO.File.Exists(path))
		//	{
		//		return Json(new { status = true, fileSize = new FileInfo(path).Length });
		//	}
		//	else
		//	{
		//		return Json(new { status = false });
		//	}
		//}
	}
}

Views/Azure/Index - Copy.cshtml
@model UploadingLagreFiles_JavaScriptFileSplit.Controllers.AzureStorageSASResult
@{
	Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
	<title>Upload</title>
	<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.6.0.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/lib/azurestoragejs-3.0.100/bundle/azure-storage.blob.js"></script>
	@*<script src="~/lib/azurestoragejs-3.0.100/bundle/azure-storage.blob.min.js"></script>*@
</head>

<body>
	<div class="modal-dialog">
		<div class="modal-content">
			<form asp-controller="Home" asp-action="UploadSmallFile" enctype="multipart/form-data" id="BlobUploadForm"
				  method="post" class="form-label-left" role="form">
				<div class="modal-body">
					<div class="form-group">
						<div class="input-group">
							<label class="input-group-btn">
								<span class="btn btn-primary">
									Browse… <input type="file" style="display: none;" name="file" id="FileInput">
								</span>
							</label>
							<input type="text" class="form-control" readonly="" id="BrowseInput">
						</div>
					</div>
					<div class="form-group">
						<div class="input-group">
							<button type="button" value="Upload to Blob" class="btn btn-success" id="UploadBlob" onclick="uploadBlob()">
								Upload to Blob
							</button>
						</div>
					</div>
					<div class="form-group hidden" id="uploadProgressBarContainer">
						Uploading...
						<div class="progress">
							<div class="progress-bar" role="progressbar" id="uploadProgressBar" aria-valuenow="60"
								 aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
								0%
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>

	<script type="text/javascript">
		$(document).on('change', '#FileInput', function () {
			var file = this.files.length > 0 ? this.files[0] : null;
			
			var acceptFileTypes = /(\.|\/)(zip)$/i;
			if (file && !acceptFileTypes.test(file.name)) {
				console.log('Not Allowed type');
				this.value = '';
			}

			var maxSize = 1024 * 1024 * 20;
			if (file && file.size > maxSize) {
				console.log('Not Allowed size');
				this.value = '';
			}

			$('#BrowseInput').val(this.value.replace(/\\/g, '/').replace(/.*\//, ''));
			if (this.value == '') {
				return false;
			}
			else {
				uploadBlob();
				return true;
			}
		});

		function displayProcess(process) {
			document.getElementById("uploadProgressBar").style.width = process + '%';
			document.getElementById("uploadProgressBar").innerHTML = process + '%';
		}

		function uploadBlob() {
			displayProcess(0);
			document.getElementById("uploadProgressBarContainer").classList.remove('hidden');

			// TODO: Call API to get URL, SAS Token, Container name
			var blobUri = '@Html.Raw(Model.AccountUrl)';
			var containerName = '@Html.Raw(Model.ContainerName)';
			var blobName = '@Html.Raw(Model.BlobName)';
			var sasToken = '@Html.Raw(Model.SASToken)';

			// https://vschooldev.blob.core.windows.net/lor/test.zip?sv=2019-10-10&st=2021-08-16T14%3A12%3A58Z&se=2021-08-17T14%3A12%3A58Z&sr=b&sp=racwdx&sig=lhgI4eDXzVL%2BdAb8281%2FbTNCYw0CKJ7VCtFV4VaUW9g%3D
			//var sasToken = 'sv=2019-10-10&st=2021-08-16T14%3A12%3A58Z&se=2021-08-17T14%3A12%3A58Z&sr=b&sp=racwdx&sig=lhgI4eDXzVL%2BdAb8281%2FbTNCYw0CKJ7VCtFV4VaUW9g%3D';

			AzureStorage.Blob.Constants.DEFAULT_PARALLEL_OPERATION_THREAD_COUNT = 1

			var blobService = AzureStorage.Blob.createBlobServiceWithSas(blobUri, sasToken).withFilter(cancelUploadFilter);

			var file = $('#FileInput').get(0).files[0];

			var customBlockSize = 1024 * 100;
			blobService.singleBlobPutThresholdInBytes = customBlockSize;
			blobService.parallelOperationThreadCount = 1;

			var uploadOptions = {
				blockSize: customBlockSize,
				parallelOperationThreadCount: 1,
				metadata: {
					isTemp: true
				}
			};

			cancelUploadFilter.cancel = false;
			cancelUploadFilter.onCancelComplete = function () {
				console.log('Cancelling complete');
			};

			var finishedOrError = false;
			var speedSummary = blobService.createBlockBlobFromBrowserFile(containerName, blobName, file, uploadOptions, function (error, result, response) {
				finishedOrError = true;
				if (error) {
					alert('Error');
				} else {
					displayProcess(100);
				}
			});

			function refreshProgress() {
				setTimeout(function () {
					if (!finishedOrError) {
						var process = speedSummary.getCompletePercent();
						displayProcess(process);
						refreshProgress();
					}
				}, 200);
			}

			refreshProgress();
		}

		// Filter allowing us to cancel an in-progress upload by setting 'cancel' to true.
		// This doesn't cancel file chunks currently being uploaded, so the upload does continue 
		// for a while after this is triggered. If the last chunks have already been sent the 
		// upload might actually complete (??)
		// See http://azure.github.io/azure-storage-node/StorageServiceClient.html#withFilter
		var cancelUploadFilter = {
			cancel: false,              // Set to true to cancel an in-progress upload

			loggingOn: false,            // Set to true to see info on console

			onCancelComplete: null,     // Set to a function you want called when a cancelled request is (probably?) complete, 
			// i.e. when returnCounter==nextCounter. Because when you cancel an upload it can be many 
			// seconds before the in-progress chunks complete. 

			// Internal from here down

			nextCounter: 0,             // Increments each time next() is called. a.k.a. 'SentChunks' ? 
			returnCounter: 0,           // Increments each time next()'s callback function is called. a.k.a. 'ReceivedChunks'?
			handle: function (requestOptions, next) {
				var self = this;
				if (self.cancel) {
					self.log('cancelling before chunk sent');
					return;
				}
				if (next) {
					self.nextCounter++;
					next(requestOptions, function (returnObject, finalCallback, nextPostCallback) {
						self.returnCounter++;
						if (self.cancel) {
							self.log('cancelling after chunk received');
							if (self.nextCounter == self.returnCounter && self.onCancelComplete) {
								self.onCancelComplete();
							}

							// REALLY ??? Is this the right way to stop the upload?
							return;
						}
						if (nextPostCallback) {
							nextPostCallback(returnObject);
						} else if (finalCallback) {
							finalCallback(returnObject);
						}
					});
				}
			},
			log: function (msg) {
				if (this.loggingOn) {
					console.log('cancelUploadFilter: ' + msg + ' nc: ' + this.nextCounter + ', rc: ' + this.returnCounter);
				}
			},
		};
	</script>
</body>
</html>

Views/Azure/Index.cshtml
@model UploadingLagreFiles_JavaScriptFileSplit.Controllers.AzureStorageSASResult
@{
	Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
	<title>Upload</title>
	@*<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.6.0.min.js"></script>*@
	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
	<script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
	<script src="~/lib/azurestoragejs-3.0.100/bundle/azure-storage.blob.js"></script>
	@*<script src="~/lib/azurestoragejs-3.0.100/bundle/azure-storage.blob.min.js"></script>*@
	<script src="~/js/jquery.azure-file-upload.js"></script>
</head>

<body>
	<div class="modal-dialog">
		<div class="modal-content">
			<form id="BlobUploadForm"
				  data-ajax="true"
				  data-ajax-method="POST"
				  data-ajax-url="@Url.Action("Index", "Azure")"
				  data-ajax-begin="ajax_begin"
				  data-ajax-success="ajax_success"
				  data-ajax-failure="ajax_failure"
				  data-ajax-complete="ajax_complete"
				  class="form-label-left"
				  role="form">
				<div class="modal-body">
					<div class="form-group">
						<div class="input-group">
							<label class="input-group-btn">
								<span class="btn btn-primary">
									Browse… <input type="file" style="display: none;" name="file" id="FileInput">
									<input type="hidden" id="azurePath" name="azurePath" />
								</span>
							</label>
							<input type="text" class="form-control" readonly="" id="BrowseInput">
						</div>
					</div>
					<div class="form-group">
						<div class="input-group">
							<button type="submit" value="Upload to Blob" class="btn btn-success" id="UploadBlob">
								Upload to Blob
							</button>
						</div>
					</div>
					<div class="form-group hidden" id="uploadProgressBarContainer">
						Uploading...
						<div class="progress">
							<div class="progress-bar" role="progressbar" id="uploadProgressBar" aria-valuenow="60"
								 aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
								0%
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>

	<script type="text/javascript">

		var fileupload = $('#FileInput').AzureFileUpload({
			blobServiceUri: '@Html.Raw(Model.AccountUrl)',
			containerName: '@Html.Raw(Model.ContainerName)',
			blobName: '@Html.Raw(Model.BlobName)',
			sasToken: '@Html.Raw(Model.SASToken)',
			blobMetaData: {
				isTemp: true,
			},
			autoUpload: true,
			acceptFileTypes: /(\.|\/)(gif|jpe?g|png|pdf|zip|rar)$/i,
			maxFileSize: 1024 * 1024 * 20,
			maxChunkSize: 1024 * 1024,
			logging: true,
			messages: {
				acceptFileTypes: 'يجب ان  يكون الملف من نوع zip',
				maxFileSize: 'لا يمكن ان يتجاوز حجم الملف 10 ميجابايت'
			},
			onSelect: function (azure, file) { },
			onStart: function (azure, file) {
				document.getElementById("uploadProgressBarContainer").classList.remove('hidden');
			},
			onProgress: function (azure, file, progress) {
				document.getElementById("uploadProgressBar").style.width = progress + '%';
				document.getElementById("uploadProgressBar").innerHTML = progress + '%';
			},
			onCacnel: function (azure, file) { },
			onError: function (azure, file, error) { },
			onFinish: function (azure, file, blobName) {
				$('#azurePath').val(blobName);
			},
		});

		function submit(e) {
		}

		function ajax_begin() {
			console.log('ajax_begin');

			$('#UploadBlob').prop("disabled", true);
			$('#FileInput').prop("disabled", true);
		}

		function ajax_success() {
			console.log('ajax_success');
		}

		function ajax_failure() {
			console.log('ajax_failure');
		}

		function ajax_complete() {
			console.log('ajax_complete');

			$('#UploadBlob').prop("disabled", false);
			$('#FileInput').prop("disabled", false);
		}

	</script>
</body>
</html>